# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, selenium-test-changes ]

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.SELENIUM_SECRET }}
        repository: mrsagar105/selenium-test-repo
        event-type: run-selenium-test
		

